
# github: https://github.com/my127/docker-magento2-console
# dockerhub: https://hub.docker.com/r/my127/magento2-console
# 
# NOTE: This image is provided to speed up the build time but all
# the files needed and used are in './root'

FROM my127/magento2-console:7.1-fpm-stretch

COPY .my127ws/docker/image/console/root /

ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
RUN chown build:build /app
COPY --chown=build:build .my127ws/skeleton       /home/build/skeleton
COPY --chown=build:build ./                      /app
COPY                     ./.my127ws/docker/stack /stack
USER build
RUN rm -rf /app/.my127ws
RUN app.build pass-1
USER root
{% else %}
VOLUME /app
VOLUME /home/build/skeleton
{% endif %}

ENTRYPOINT /entrypoint.sh
